import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Table from './components/Table'
import {generateRandomObjs, NUM, formatDollars, WORDNUM} from './common/utils'

class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      objs: []
    }
  }

  generateData() {
        // TODO maybe seperate the headers from the autoGenerated information....
        let that = this
        let generateData = [{
          field: "firstName",
          maxSize: 12
        }, {
          field: "lastName",
          maxSize: 12
        }, {
          field: "phone",
          type: WORDNUM,
          maxSize: 10,
          minSize: 10,
          format: phone => {
            let s = String(phone)
            return s.substring(0, 3) + "-" + s.substr(3, 4) + "-" + s.substr(6)
          }
        }, {
          field: "address",
          maxSize: 40,
          minSize: 12
        }, {
          field: "state",
          maxSize: 20,
          minSize: 5
        }, {
          field: "age",
          maxSize: 2,
          minSize: 1,
          type: NUM
        }, {
          field: "salary",
          maxSize: 9,
          minSize: 4,
          type: NUM,
          format: formatDollars
        }]
        return generateData
  }

  headers() {
    // TODO maybe seperate the headers from the autoGenerated information....
    let that = this
    let headers = [{
      name: "First Name",
      field: "firstName",
    }, {
      name: "Last Name",
      field: "lastName",
    }, {
      name: "Phone",
      field: "phone",
    }, {
      name: "Address",
      field: "address",
    }, {
      name: "State",
      field: "state",
    }, {
      name: "Age",
      field: "age",
    }, {
      name: "Salary",
      field: "salary"
    }, {
      name: "Delete",
      key: "id",
      // SHOW seperate the Delete Button from the Props Component
      component: function (props) {
        let deleteTheObject = () => {
          let index = that.state.objs.findIndex((obj) => {
            return obj.id === props.data.id
          })
          that.state.objs.splice(index, 1)
          that.setState(that.state)
        }
        return <button className="setTableComponet" onClick={() => deleteTheObject()}>DELETE</button>
      }
    }]
    return headers
  }

  componentWillMount() {
    setTimeout(() => {
      let objs = generateRandomObjs(this.generateData(), 1800)
      this.setState({objs: objs})
    }, 100)
  }

  render() {
    // SHOW how to make the table into a sortable table with the headers
    // SHOW how to add in component elements to change the size of the cell in the table
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div className="container">
          <Table data={this.state.objs} headers={this.headers()} id="id" />
        </div>
      </div>
    );
  }
}

export default App;
