import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import Pagination from './components/Pagination'
import {generateRandomObjs, NUM, formatDollars, WORDNUM} from './common/utils'

class App extends Component {
  constructor(props) {
    super(props)
  }

  headers() {
    // TODO maybe seperate the headers from the autoGenerated information....
    let that = this
    let headers = [{
      name: "First Name",
      field: "firstName",
      maxSize: 12
    }, {
      name: "Last Name",
      field: "lastName",
      maxSize: 12
    }, {
      name: "Phone",
      field: "phone",
      type: WORDNUM,
      maxSize: 10,
      minSize: 10,
      format: phone => {
        let s = String(phone)
        return s.substring(0, 3) + "-" + s.substr(3, 4) + "-" + s.substr(6)
      }
    }, {
      name: "Address",
      field: "address",
      maxSize: 40,
      minSize: 12
    }, {
      name: "State",
      field: "state",
      maxSize: 20,
      minSize: 5
    }, {
      name: "Age",
      field: "age",
      maxSize: 2,
      minSize: 1,
      type: NUM
    }, {
      name: "Salary",
      field: "salary",
      maxSize: 9,
      minSize: 4,
      type: NUM,
      format: formatDollars
    }, {
      name: "Delete",
      key: "id",
      // SHOW seperate the Delete Button from the Props Component
      component: function (pagination) {
        return function (props) {
          let deleteTheObject = () => {
            pagination.remove(props.data.id)
          }
          return <button className="setTableComponet" onClick={() => deleteTheObject()}>DELETE</button>
        }
      }
    }]
    return headers
  }

  render() {
    // SHOW how to make the table into a sortable table with the headers
    // SHOW how to add in component elements to change the size of the cell in the table
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div className="container">
          <Pagination getData={(num) => generateRandomObjs(this.headers(), num)} headers={this.headers()} id="id" />
        </div>
        <div className="bottom-page"/>
      </div>
    );
  }
}

export default App;
